services:
  db:
    container_name: db
    image: postgres:15-alpine
    networks:
      - default
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-sap_reform}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  app:
    container_name: sap
    build:
      context: .
      dockerfile: Dockerfile
    image: razorcut777/sap-reform:v1.0
    restart: always
    networks:
      - default
    command: >
      sh -c "if [ ! -d 'postgres_data' ]; then
        node node_modules/prisma/build/index.js db push && 
        node node_modules/prisma/build/index.js db seed && 
        node server.js;
      else
        echo 'Folder exists, skipping command';
      fi"
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://0.0.0.0:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      ALLOWED_EMAILS: ${ALLOWED_EMAILS}
    # ports:
    #   - "3000:3000"
    depends_on:
      - db

  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db

volumes:
  postgres_data: